"""
capstone_demo.py  ·  Days 56-60  ·  May 2-6
---------------------------------------------
Goes into: day9_multiagent/  (extended)

Phase 2 Capstone Demo — runs the complete InsightBot pipeline
end-to-end with all safety layers, streaming, and cloud readiness.

This is the final submission for Phase 2.

Usage:
    python capstone_demo.py           # full demo
    python capstone_demo.py --report  # generate capstone report + visual
"""

import json
import os
import glob
import argparse
from datetime import datetime
from pathlib import Path


def run_full_pipeline(query: str = "Analyse customer churn and build a predictive model") -> dict:
    """Run the complete InsightBot pipeline with all safety layers."""
    print("=" * 65)
    print("InsightBot — Phase 2 Capstone Demo")
    print("=" * 65)
    print(f"Query: {query}")
    print()

    results = {}

    # Step 1 — Guardrails check
    print("[Step 1] Safety check — NeMo Guardrails + PII scan")
    from nemo_guardrails import apply_guardrails
    guard_result = apply_guardrails(query)
    print(f"  Status:   {guard_result['status']}")
    print(f"  Redacted: {guard_result.get('redacted', False)}")
    results["guardrails"] = guard_result
    if guard_result["status"] == "blocked":
        print(f"  Blocked:  {guard_result['reason']}")
        return results

    # Step 2 — InsightBot 5-agent pipeline
    print("\n[Step 2] InsightBot multi-agent analysis")
    from insightbot import run_demo_insightbot
    bot_result = run_demo_insightbot(query)
    print(f"  Agents:  {bot_result['agents_used']}")
    print(f"  Quality: {bot_result['quality']}/10")
    results["insightbot"] = bot_result

    # Step 3 — Eval quality check
    print("\n[Step 3] MT-Bench quality evaluation")
    from eval_observability import run_mt_bench, run_helm_summary
    mt   = run_mt_bench(model_name="demo")
    helm = run_helm_summary(mt)
    print(f"  MT-Bench avg: {sum(r['avg_score'] for r in mt)/len(mt):.1f}%")
    print(f"  HELM accuracy: {helm['accuracy']}%")
    results["evaluation"] = {"mt_bench": mt, "helm": helm}

    # Step 4 — Cloud readiness check
    print("\n[Step 4] Cloud deployment readiness")
    from cloud_deploy import DEPLOY_CONFIG
    print(f"  AWS endpoint:   {DEPLOY_CONFIG['aws']['endpoint_name']}")
    print(f"  Azure endpoint: {DEPLOY_CONFIG['azure']['endpoint_name']}")
    print(f"  Model:          {DEPLOY_CONFIG['model_name']}")
    print(f"  Ready to deploy: YES (run cloud_deploy.py --provider aws)")
    results["cloud"] = {"status": "ready", "config": DEPLOY_CONFIG}

    # Step 5 — Save final capstone report
    print("\n[Step 5] Saving Phase 2 capstone report")
    report = _build_capstone_report(query, results)
    results["report_path"] = report

    print("\n" + "=" * 65)
    print(f"Phase 2 Capstone Complete")
    print(f"Report: {report}")
    print("=" * 65)

    return results


def _build_capstone_report(query: str, results: dict) -> str:
    Path("outputs").mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    bot     = results.get("insightbot", {})
    helm    = results.get("evaluation", {}).get("helm", {})
    quality = bot.get("quality", 0)

    lines = [
        "# Phase 2 Capstone — InsightBot Demo Report",
        f"**Student:** Sheshikala | **IIT Indore AI & DS**",
        f"**Date:** {datetime.now().strftime('%B %d, %Y')}",
        "",
        "---",
        "",
        "## Pipeline Components",
        "",
        "| Layer | Component | Status |",
        "|-------|-----------|--------|",
        "| Safety | NeMo Guardrails + Presidio PII | Active |",
        "| Agents | 5-agent CrewAI pipeline | Active |",
        "| Streaming | FastAPI SSE real-time | Ready |",
        "| Evaluation | MT-Bench + HELM | Scored |",
        "| Cloud | AWS SageMaker + Azure ML | Ready |",
        "",
        f"## Query",
        f"> {query}",
        "",
        f"## Result",
        "",
        bot.get("report", "Report generated by InsightBot pipeline."),
        "",
        "---",
        "",
        "## Evaluation Scores",
        "",
        f"- Quality score: {quality}/10",
        f"- HELM accuracy: {helm.get('accuracy', 'N/A')}%",
        f"- MT-Bench tasks: {len(results.get('evaluation', {}).get('mt_bench', []))}",
        "",
        "---",
        "",
        "## Phase 2 Milestones Completed",
        "",
        "- M6: DataOracle LLM Insights Predictor (day10_project/)",
        "- M7: TimeSeriesHunter QLoRA Llama 3.1 (day13/)",
        "- M8: InsightBot Multi-Agent Data Analyst (day9_multiagent/)",
        "",
        "**Ready for Phase 3: Agentic AI and Cloud Deploy**",
    ]

    md_path = f"outputs/Phase2_Capstone_{ts}.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    json_path = f"outputs/Phase2_Capstone_{ts}.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({
            "query": query,
            "quality": quality,
            "helm": helm,
            "timestamp": ts,
        }, f, indent=2)

    print(f"  MD   -> {md_path}")
    print(f"  JSON -> {json_path}")
    return md_path


def generate_visual_report():
    """Generate a visual PNG capstone report card."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches

    Path("outputs").mkdir(exist_ok=True)

    fig = plt.figure(figsize=(14, 8), facecolor="#0f0f1a")
    ax  = fig.add_subplot(111)
    ax.set_facecolor("#0f0f1a")
    ax.axis("off")

    TEXT  = "#e2e8f0"
    MUTED = "#94a3b8"
    PURPLE = "#7c6ff7"
    GREEN  = "#4ade80"
    AMBER  = "#fbbf24"
    DARK   = "#1a1a2e"

    # Title
    fig.text(0.5, 0.93, "Phase 2 Capstone — InsightBot",
             ha="center", fontsize=20, fontweight="bold", color=TEXT)
    fig.text(0.5, 0.87, "Sheshikala  |  IIT Indore AI & DS  |  Apr 22 – May 6",
             ha="center", fontsize=11, color=MUTED)

    # Pipeline boxes
    components = [
        ("NeMo\nGuardrails", "Day 46", PURPLE, "PII + Safety"),
        ("FastAPI\nSSE",      "Day 47", AMBER,  "Streaming"),
        ("Cloud\nDeploy",     "D48-50", "#38bdf8", "AWS + Azure"),
        ("Phase 2\nReview",   "D51-55", GREEN,  "M6+M7+M8"),
        ("Capstone\nDemo",    "D56-60", "#fb7185", "Final Report"),
    ]

    box_w, box_h = 0.13, 0.22
    gap = 0.015
    start_x = 0.08
    y = 0.55

    for i, (name, day, color, sub) in enumerate(components):
        x = start_x + i * (box_w + gap)
        rect = mpatches.FancyBboxPatch(
            (x, y), box_w, box_h,
            boxstyle="round,pad=0.01",
            facecolor=color, alpha=0.15,
            edgecolor=color, linewidth=1.5,
            transform=fig.transFigure, figure=fig
        )
        fig.add_artist(rect)
        fig.text(x + box_w/2, y + box_h - 0.04, name,
                 ha="center", fontsize=9, fontweight="bold",
                 color=color, transform=fig.transFigure)
        fig.text(x + box_w/2, y + 0.06, day,
                 ha="center", fontsize=8, color=MUTED,
                 transform=fig.transFigure)
        fig.text(x + box_w/2, y + 0.025, sub,
                 ha="center", fontsize=7.5, color=TEXT,
                 transform=fig.transFigure)

        if i < len(components) - 1:
            fig.text(x + box_w + gap/2, y + box_h/2,
                     ">", ha="center", fontsize=14,
                     color=MUTED, transform=fig.transFigure)

    # Milestone row
    milestones = [
        ("M6 DataOracle",          "day10_project/", "86%",  GREEN),
        ("M7 TimeSeriesHunter",    "day13/",          "86%",  GREEN),
        ("M8 InsightBot",          "day9_multiagent/","8.5/10", GREEN),
    ]

    fig.text(0.5, 0.47, "Phase 2 Milestones", ha="center",
             fontsize=12, color=TEXT, fontweight="bold")

    for i, (name, folder, score, color) in enumerate(milestones):
        x = 0.12 + i * 0.30
        rect = mpatches.FancyBboxPatch(
            (x, 0.28), 0.26, 0.14,
            boxstyle="round,pad=0.01",
            facecolor=color, alpha=0.12,
            edgecolor=color, linewidth=1,
            transform=fig.transFigure, figure=fig
        )
        fig.add_artist(rect)
        fig.text(x + 0.13, 0.38, name,
                 ha="center", fontsize=9, fontweight="bold",
                 color=color, transform=fig.transFigure)
        fig.text(x + 0.13, 0.33, folder,
                 ha="center", fontsize=8, color=MUTED,
                 transform=fig.transFigure)
        fig.text(x + 0.13, 0.29, f"Score: {score}",
                 ha="center", fontsize=8, color=TEXT,
                 transform=fig.transFigure)

    # Footer
    fig.text(0.5, 0.06,
             "llm-engineering-60days/day9_multiagent/  |  "
             "git commit -m \"day56-60(Phase2): InsightBot capstone + cloud deploy demo\"",
             ha="center", fontsize=8, color=MUTED, family="monospace")

    ts  = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = f"outputs/Phase2_Capstone_Visual_{ts}.png"
    fig.savefig(out, dpi=180, bbox_inches="tight", facecolor="#0f0f1a")
    plt.close()
    print(f"Visual report saved -> {out}")
    return out


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Phase 2 Capstone Demo")
    parser.add_argument("--report", action="store_true")
    parser.add_argument("--query",  default=None)
    args = parser.parse_args()

    query = args.query or "Analyse customer churn patterns and build a predictive model"

    if args.report:
        generate_visual_report()
    else:
        run_full_pipeline(query)
        generate_visual_report()
