"""
Day 12: MongoDB CRUD Operations
Author: Sheshikala
Date: 2026-03-12

What I learned:
- MongoDB stores data as documents (like JSON) not rows like SQL
- No fixed schema needed - each document can have different fields
- This is really useful for ML experiments where hyperparameters differ per model
- _id is auto-generated by MongoDB
- find() returns a cursor not a list - need list() to see all results
- dot notation (metrics.test_f1) to access nested fields in queries

How to run:
  1. Start MongoDB: docker run -d -p 27017:27017 --name mongodb mongo
  2. pip install pymongo
  3. python mongo_crud.py
"""

from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
import datetime

# ─────────────────────────────────────────────
# CONNECTION
# ─────────────────────────────────────────────
def get_db():
    try:
        client = MongoClient("mongodb://localhost:27017/", serverSelectionTimeoutMS=3000)
        client.admin.command("ping")
        print("✅ Connected to MongoDB!")
        return client["ml_tracker"]
    except ConnectionFailure:
        print("❌ MongoDB not running!")
        print("   Run: docker run -d -p 27017:27017 --name mongodb mongo")
        exit(1)


# ─────────────────────────────────────────────
# 1. CREATE
# ─────────────────────────────────────────────
def create_documents(db):
    print("\n── CREATE ──────────────────────────────")
    col = db["experiments"]
    col.drop()  # fresh start

    # insert_one - I used nested dict for hyperparameters
    # different models have different HPs so this flexible schema is perfect
    col.insert_one({
        "name"           : "BERT Sentiment Classifier",
        "model_type"     : "BERT",
        "researcher"     : "Sheshikala",
        "project"        : "Sentiment Analysis",
        "hyperparameters": {
            "learning_rate": 2e-5,
            "epochs"       : 3,
            "batch_size"   : 32,
            "optimizer"    : "AdamW",
            "warmup_steps" : 500
        },
        "metrics": {
            "train_f1"     : 0.9395,
            "val_f1"       : 0.9065,
            "test_f1"      : 0.9020,
            "test_accuracy": 0.9050
        },
        "tags"         : ["NLP", "Transformer", "Classification"],
        "status"       : "completed",
        "training_hours": 2.5,
        "created_at"   : datetime.datetime.now()
    })
    print("  ✅ insert_one  → BERT experiment added")

    # insert_many - more efficient than calling insert_one multiple times
    col.insert_many([
        {
            "name"           : "RoBERTa Sentiment",
            "model_type"     : "RoBERTa",
            "researcher"     : "Sheshikala",
            "project"        : "Sentiment Analysis",
            "hyperparameters": {"learning_rate": 1e-5, "epochs": 5, "batch_size": 16},
            "metrics"        : {"test_f1": 0.9360, "test_accuracy": 0.9380},
            "tags"           : ["NLP", "Transformer"],
            "status"         : "completed",
            "training_hours" : 4.2,
            "created_at"     : datetime.datetime.now()
        },
        {
            "name"           : "DistilBERT Fast",
            "model_type"     : "DistilBERT",
            "researcher"     : "Sheshikala",
            "project"        : "Sentiment Analysis",
            "hyperparameters": {"learning_rate": 3e-5, "epochs": 4, "batch_size": 64},
            "metrics"        : {"test_f1": 0.8985, "test_accuracy": 0.9010},
            "tags"           : ["NLP", "Transformer", "Lightweight"],
            "status"         : "completed",
            "training_hours" : 1.5,
            "created_at"     : datetime.datetime.now()
        },
        {
            "name"           : "ResNet50 Medical",
            "model_type"     : "ResNet50",
            "researcher"     : "Sheshikala",
            "project"        : "Medical Imaging",
            "hyperparameters": {"learning_rate": 1e-4, "epochs": 20, "pretrained": True},
            "metrics"        : {"test_f1": 0.8530, "test_accuracy": 0.8580},
            "tags"           : ["CV", "Transfer Learning"],
            "status"         : "completed",
            "training_hours" : 10.0,
            "created_at"     : datetime.datetime.now()
        },
        {
            "name"           : "XGBoost Fraud Detector",
            "model_type"     : "XGBoost",
            "researcher"     : "Sheshikala",
            "project"        : "Fraud Detection",
            "hyperparameters": {"n_estimators": 500, "max_depth": 6, "learning_rate": 0.05},
            "metrics"        : {"test_f1": 0.9279, "auc_pr": 0.836},
            "tags"           : ["Tabular", "Ensemble"],
            "status"         : "running",
            "training_hours" : 0.75,
            "created_at"     : datetime.datetime.now()
        },
        {
            "name"           : "LightGBM Forecasting",
            "model_type"     : "LightGBM",
            "researcher"     : "Sheshikala",
            "project"        : "Sales Forecasting",
            "hyperparameters": {"n_estimators": 300, "num_leaves": 31, "learning_rate": 0.1},
            "metrics"        : {"test_f1": 0.9015, "rmse": 2250.60},
            "tags"           : ["Tabular", "Forecasting"],
            "status"         : "completed",
            "training_hours" : 0.5,
            "created_at"     : datetime.datetime.now()
        }
    ])
    print(f"  ✅ insert_many → 5 more experiments added")
    print(f"  Total documents: {col.count_documents({})}")


# ─────────────────────────────────────────────
# 2. READ
# ─────────────────────────────────────────────
def read_documents(db):
    print("\n── READ ────────────────────────────────")
    col = db["experiments"]

    # find_one - returns first matching document
    doc = col.find_one({"model_type": "BERT"})
    print(f"  find_one BERT  → {doc['name']} | f1: {doc['metrics']['test_f1']}")

    # find with projection - 1=include 0=exclude
    print("\n  All completed experiments:")
    for doc in col.find({"status": "completed"}, {"name": 1, "model_type": 1, "metrics.test_f1": 1, "_id": 0}):
        print(f"    {doc['model_type']:15s} | {doc['name']:28s} | f1: {doc['metrics'].get('test_f1','N/A')}")

    # comparison operators: $gt $lt $gte $lte $ne
    print("\n  Models with f1 > 0.92:")
    for doc in col.find({"metrics.test_f1": {"$gt": 0.92}}, {"name": 1, "metrics.test_f1": 1, "_id": 0}):
        print(f"    {doc['name']} → {doc['metrics']['test_f1']}")

    # sort + limit - like ORDER BY LIMIT in SQL
    print("\n  Top 3 by F1 score:")
    top3 = col.find({}, {"name": 1, "metrics.test_f1": 1, "_id": 0}).sort("metrics.test_f1", -1).limit(3)
    for i, doc in enumerate(top3, 1):
        print(f"    #{i} {doc['name']:28s} → {doc['metrics'].get('test_f1','N/A')}")

    # count documents
    total     = col.count_documents({})
    completed = col.count_documents({"status": "completed"})
    print(f"\n  Count → total: {total} | completed: {completed} | other: {total - completed}")


# ─────────────────────────────────────────────
# 3. UPDATE
# ─────────────────────────────────────────────
def update_documents(db):
    print("\n── UPDATE ──────────────────────────────")
    col = db["experiments"]

    # update_one with $set and $push
    # $set changes fields, $push adds item to array
    result = col.update_one(
        {"name": "XGBoost Fraud Detector"},
        {
            "$set" : {"status": "completed", "metrics.test_f1": 0.9310},
            "$push": {"tags": "Production-Ready"}
        }
    )
    print(f"  update_one     → matched: {result.matched_count} | modified: {result.modified_count}")

    # update_many - add domain field to all NLP experiments
    result = col.update_many(
        {"tags": "NLP"},
        {"$set": {"domain": "Natural Language Processing"}}
    )
    print(f"  update_many    → NLP domain field added to {result.modified_count} docs")

    # upsert - creates document if it doesn't exist
    col.update_one(
        {"name": "LSTM Time Series"},
        {"$set": {
            "model_type": "LSTM",
            "project"   : "Sales Forecasting",
            "status"    : "pending",
            "researcher": "Sheshikala",
            "created_at": datetime.datetime.now()
        }},
        upsert=True
    )
    print(f"  upsert         → LSTM created (didn't exist before)")
    print(f"  Total now      → {col.count_documents({})}")


# ─────────────────────────────────────────────
# 4. QUERY OPERATORS
# ─────────────────────────────────────────────
def query_operators(db):
    print("\n── QUERY OPERATORS ─────────────────────")
    col = db["experiments"]

    # $in - match any value in a list
    print("  $in  - BERT or RoBERTa models:")
    for doc in col.find({"model_type": {"$in": ["BERT", "RoBERTa"]}}, {"name": 1, "_id": 0}):
        print(f"    {doc['name']}")

    # $exists - check if a field exists
    print("\n  $exists - experiments with rmse metric:")
    for doc in col.find({"metrics.rmse": {"$exists": True}}, {"name": 1, "metrics.rmse": 1, "_id": 0}):
        print(f"    {doc['name']} → rmse: {doc['metrics']['rmse']}")

    # $and - multiple conditions must all be true
    print("\n  $and - completed NLP experiments:")
    for doc in col.find({"$and": [{"status": "completed"}, {"tags": "NLP"}]}, {"name": 1, "_id": 0}):
        print(f"    {doc['name']}")

    # $regex - pattern matching (like LIKE in SQL)
    print("\n  $regex - name contains 'Sentiment':")
    for doc in col.find({"name": {"$regex": "Sentiment", "$options": "i"}}, {"name": 1, "_id": 0}):
        print(f"    {doc['name']}")

    # $elemMatch - match element inside array
    print("\n  $elemMatch - has 'Transformer' tag:")
    for doc in col.find({"tags": {"$elemMatch": {"$eq": "Transformer"}}}, {"name": 1, "tags": 1, "_id": 0}):
        print(f"    {doc['name']} → {doc['tags']}")


# ─────────────────────────────────────────────
# 5. INDEXES
# ─────────────────────────────────────────────
def create_indexes(db):
    print("\n── INDEXES ─────────────────────────────")
    col = db["experiments"]

    # single field indexes - makes queries on these fields faster
    col.create_index("model_type")
    col.create_index("status")
    col.create_index("researcher")

    # compound index - for queries filtering by project AND status together
    col.create_index([("project", 1), ("status", 1)])

    # text index - for full text search on name field
    col.create_index([("name", "text")])

    print("  Created indexes: model_type, status, researcher, project+status, text(name)")
    print("  All indexes on collection:")
    for idx in col.list_indexes():
        print(f"    {idx['name']}")


# ─────────────────────────────────────────────
# 6. DELETE
# ─────────────────────────────────────────────
def delete_documents(db):
    print("\n── DELETE ──────────────────────────────")
    col = db["experiments"]

    # delete_one
    result = col.delete_one({"name": "LSTM Time Series"})
    print(f"  delete_one     → deleted: {result.deleted_count} (LSTM)")

    # delete_many - careful, deletes all matching!
    result = col.delete_many({"status": "pending"})
    print(f"  delete_many    → deleted: {result.deleted_count} pending experiments")

    print(f"  Remaining      → {col.count_documents({})} documents")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
if __name__ == "__main__":
    db = get_db()
    create_documents(db)
    read_documents(db)
    update_documents(db)
    query_operators(db)
    create_indexes(db)
    delete_documents(db)
    print("\n✅ mongo_crud.py completed! Run agg_pipeline.py next")
