# -*- coding: utf-8 -*-
"""decision_tree.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnnvjWl3gQTieoEi4BySJDTARXmhEZWK
"""

#step1: import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#step2:loading the dataset
import os
import pandas as pd

# ---------- Universal Dataset Loader ----------

def load_data(filename):
    possible_paths = [
        filename,                      # same folder
        f"data/{filename}",            # project/data folder
        f"/content/{filename}",        # Colab direct upload
        f"/content/data/{filename}"    # Colab data folder
    ]

    for path in possible_paths:
        if os.path.exists(path):
            print(f"Loaded file from: {path}")
            return pd.read_csv(path)

    raise FileNotFoundError("Dataset not found in any expected location.")

# Load dataset
df = load_data("heart.csv")

#step3: EDA
df.head()

df.shape

df['target'].value_counts()

df.info()

#step4: data cleaning
df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

# step5: check for outliers

col = list(df.columns)

for col in df.columns:
    if df[col].dtype != 'object':
        sns.boxplot(df[col])
        plt.xlabel(col)
        plt.show()

plt.figure(figsize=(12,6))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')

df.dtypes

# step 5 - model building
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

x=df.drop('target',axis=1)
x

y=df['target']
y

np.random.seed(42)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=38)

y_test

model  = DecisionTreeClassifier()

model.fit(x_train, y_train)

y_pred=model.predict(x_test)

y_pred

# dataframe actual and prediction
comparision=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
comparision

accuracy_score(y_test,y_pred)

cm  = confusion_matrix(y_pred, y_test)
cm

from sklearn import tree
tree.plot_tree(model, fontsize = 7)

#visual map showing how the decision tree makes predictions.
plt.figure(figsize=(24,14))

tree.plot_tree(
    model,
    feature_names=x_train.columns,
    class_names=['No Disease', 'Disease'],
    filled=True,
    fontsize=12
)

plt.title("Decision Tree Visualization", fontsize=12)
plt.show()

# visual map showing how the decision tree predicts heart disease.
from sklearn import tree
from sklearn.tree import plot_tree

plt.figure(figsize=(20, 15))
tree.plot_tree(model, feature_names=x_train.columns, filled=True, class_names=['No Heart Disease', 'Heart Disease'], fontsize = 10)
plt.show()

# Hyperparameter Tuning (Decision Tree)
#Decision Tree Depth vs Accuracy
depths = [1,2,3,4,5,6,7,8,9,10,11,12,13]
for i in depths:
    model = DecisionTreeClassifier(max_depth=i, random_state=60)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"Max Depth: {i} | Accuracy: {acc:.3f}")

model.get_depth()

#Choose simplest model that gives highest accuracy.
best_model = DecisionTreeClassifier(max_depth=5, random_state=60)
best_model.fit(x_train, y_train)

plt.figure(figsize=(24,14))
plot_tree(best_model,
          feature_names=x_train.columns,
          filled=True,
          class_names=['No Heart Disease','Heart Disease'],
          fontsize=10)

plt.title("Best Decision Tree (Depth = 5)")
plt.show()



"""**Hyperparameter Tuning using GridSearchCV**


Finds the best combination of parameters for Decision Tree automatically
"""

# Hyperparameter Tuning (Grid Search)

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Create a Decision Tree model (base model)

new_model = DecisionTreeClassifier()

# Define parameter combinations to test

grid_params = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [1, 5, 50, 100],
    'random_state': [0, 1, 2, 40, 41, 42],
    'min_samples_split': [2, 3, 5, 6, 8, 9, 22],
    'min_samples_leaf': [1, 4, 6, 7, 9, 10],
    'max_features': [1, 2, 3, 4, 5, 6, 10]
}

# Grid Search with Cross Validation

gv = GridSearchCV(
    estimator=new_model,
    param_grid=grid_params,
    cv=3
)

gv.fit(x_train, y_train)

# Best parameter combination

gv.best_params_

# Get best model from grid search

dt_model = gv.best_estimator_

# Predict test data
y_pred1 = dt_model.predict(x_test)

# Accuracy
accuracy_score(y_test, y_pred1)

#Visualize Best Decision Tree
from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,12))

tree.plot_tree(dt_model,
               feature_names=x_train.columns,
               filled=True,
               fontsize=7)

plt.title("Best Decision Tree (GridSearchCV)")
plt.show()

"""**Hyperparameter Tuning using RandomizedSearchCV**


Tests random parameter combinations instead of all combinations and Much faster than GridSearch
"""

#Import RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV

#Create Model
new_model1 = DecisionTreeClassifier()

#Parameter Distribution
param_dict = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [1, 5, 50, 100],
    'random_state': [0, 1, 2, 40, 41, 42],
    'min_samples_split': [2, 3, 5, 6, 8, 9, 22],
    'min_samples_leaf': [1, 4, 6, 7, 9, 10],
    'max_features': [1, 2, 3, 4, 5, 6, 10]
}

#Run Randomized Search
rv = RandomizedSearchCV(
    estimator=new_model1,
    param_distributions=param_dict,
    cv=3,
    random_state=42,
    n_jobs=1
)

rv.fit(x_train, y_train)

#Evaluate Randomized Model
dt_model1 = rv.best_estimator_

y_pred2 = dt_model1.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred2))

# Best depth model prediction

best_model = DecisionTreeClassifier(max_depth=5, random_state=60)
best_model.fit(x_train, y_train)

y_pred_best = best_model.predict(x_test)

#Model Accuracy Comparison
print("\nModel Accuracy Comparison\n")

print("Default Decision Tree Accuracy:",
      accuracy_score(y_test, y_pred))

print("Best Depth Model Accuracy:",
      accuracy_score(y_test, y_pred_best))

print("GridSearchCV Accuracy:",
      accuracy_score(y_test, y_pred1))

print("RandomizedSearchCV Accuracy:",
      accuracy_score(y_test, y_pred2))

"""
## Conclusion

### Project Overview
- Heart disease prediction was performed using a Decision Tree model.
- Data analysis, visualization, model building, and optimization were completed.

### Data Analysis & Visualization
- Dataset explored using statistical summary and correlation heatmap.
- Boxplots helped identify data distribution and potential outliers.
- Feature relationships were analyzed before model training.

### Model Building
- Dataset split into training and testing sets.
- Initial Decision Tree model achieved accuracy ≈ **0.80**.

### Hyperparameter Tuning
- Different `max_depth` values were tested to improve performance.
- Best accuracy obtained at **max_depth = 5**.
- GridSearchCV tested all parameter combinations for optimal results.
- RandomizedSearchCV provided faster optimization with similar performance.

### Model Performance
- Best model accuracy: **0.836 (83.6%)**.
- Tuned model performed better than the default model.

### Observations
- Increasing depth initially improved accuracy.
- Higher depths increased model complexity without performance gain.
- Very deep trees indicate risk of **overfitting**.
- Simpler models provided stable and interpretable predictions.

### Key Learnings
- Hyperparameter tuning improves model performance.
- Model complexity should be controlled to avoid overfitting.
- Decision Trees are interpretable and useful for classification problems.
"""